import type { Agent, KPIData, MessageVolumeData, AgentActivityData, AgentLog, Escalation } from "@/types";

export const agents: Agent[] = [
  {
    name: "Sarah",
    role: "Guest Communication",
    status: "online",
    lastActivity: "2 minutes ago",
    todayMessages: 187,
    avatar: "S",
    color: "#b91c1c",
  },
  {
    name: "Marcus",
    role: "Review Management",
    status: "online",
    lastActivity: "5 minutes ago",
    todayMessages: 42,
    avatar: "M",
    color: "#7c3aed",
  },
  {
    name: "Olivia",
    role: "Scheduling & Staffing",
    status: "online",
    lastActivity: "12 minutes ago",
    todayMessages: 23,
    avatar: "O",
    color: "#047857",
  },
  {
    name: "Alex",
    role: "Reporting & Analytics",
    status: "offline",
    lastActivity: "1 hour ago",
    todayMessages: 8,
    avatar: "A",
    color: "#1d4ed8",
  },
];

export const kpiData: KPIData[] = [
  {
    label: "Total Messages",
    value: 324,
    formattedValue: "324",
    trend: { direction: "up", percentage: 12 },
    icon: "message-square",
  },
  {
    label: "Avg Response Time",
    value: 12,
    formattedValue: "12s",
    trend: { direction: "down", percentage: 15 },
    icon: "clock",
  },
  {
    label: "Escalations",
    value: 8,
    formattedValue: "8",
    trend: { direction: "down", percentage: 25 },
    icon: "alert-triangle",
  },
  {
    label: "Time Saved",
    value: 47,
    formattedValue: "47h",
    trend: { direction: "up", percentage: 8 },
    icon: "timer",
  },
];

export const messageVolumeData: MessageVolumeData[] = [
  { date: "Mon", messages: 280, escalations: 12 },
  { date: "Tue", messages: 310, escalations: 8 },
  { date: "Wed", messages: 295, escalations: 15 },
  { date: "Thu", messages: 340, escalations: 6 },
  { date: "Fri", messages: 380, escalations: 10 },
  { date: "Sat", messages: 420, escalations: 14 },
  { date: "Sun", messages: 324, escalations: 8 },
];

export const agentActivityData: AgentActivityData[] = [
  { name: "Sarah", value: 60, color: "#b91c1c" },
  { name: "Marcus", value: 20, color: "#7c3aed" },
  { name: "Olivia", value: 12, color: "#047857" },
  { name: "Alex", value: 8, color: "#1d4ed8" },
];

export const recentLogs: AgentLog[] = [
  {
    id: "1",
    timestamp: "2026-03-02T14:45:00Z",
    agentName: "Sarah",
    actionType: "Guest inquiry",
    guestName: "Ahmed K.",
    messagePreview: "Can I get a late checkout tomorrow? We have an afternoon flight.",
    channel: "WhatsApp",
    status: "handled",
    responseTimeSeconds: 8,
  },
  {
    id: "2",
    timestamp: "2026-03-02T14:42:00Z",
    agentName: "Marcus",
    actionType: "Review response",
    guestName: "Sarah M.",
    messagePreview: "Thank you for the wonderful review! We're delighted you enjoyed...",
    channel: "Google Reviews",
    status: "handled",
    responseTimeSeconds: 45,
  },
  {
    id: "3",
    timestamp: "2026-03-02T14:38:00Z",
    agentName: "Sarah",
    actionType: "Booking question",
    guestName: "John D.",
    messagePreview: "I need to cancel my reservation due to a family emergency...",
    channel: "WhatsApp",
    status: "escalated",
    responseTimeSeconds: 12,
  },
  {
    id: "4",
    timestamp: "2026-03-02T14:30:00Z",
    agentName: "Olivia",
    actionType: "Schedule created",
    guestName: "Staff",
    messagePreview: "Weekly schedule for housekeeping team generated and distributed.",
    channel: "Internal",
    status: "handled",
    responseTimeSeconds: 120,
  },
  {
    id: "5",
    timestamp: "2026-03-02T14:25:00Z",
    agentName: "Sarah",
    actionType: "Room service",
    guestName: "Maria L.",
    messagePreview: "Could I order breakfast to room 412? The continental please.",
    channel: "WhatsApp",
    status: "handled",
    responseTimeSeconds: 5,
  },
  {
    id: "6",
    timestamp: "2026-03-02T14:20:00Z",
    agentName: "Alex",
    actionType: "Daily report",
    guestName: "Management",
    messagePreview: "Daily revenue report generated: Total revenue $45,230...",
    channel: "Email",
    status: "handled",
    responseTimeSeconds: 300,
  },
];

export const escalations: Escalation[] = [
  {
    id: "1",
    createdAt: "2026-03-02T14:38:00Z",
    agentName: "Sarah",
    priority: "high",
    guestName: "John Davis",
    message: "I need to cancel my reservation for tomorrow due to a family emergency. Can I get a full refund?",
    reason: "Requires manager approval for refund policy exception",
    status: "pending",
  },
  {
    id: "2",
    createdAt: "2026-03-02T13:15:00Z",
    agentName: "Sarah",
    priority: "medium",
    guestName: "Lisa Chen",
    message: "The air conditioning in room 305 hasn't been working for 2 days now. Very disappointed.",
    reason: "Repeat complaint - maintenance issue unresolved",
    status: "pending",
  },
  {
    id: "3",
    createdAt: "2026-03-02T11:00:00Z",
    agentName: "Marcus",
    priority: "low",
    guestName: "Tom W.",
    message: "1-star review mentioning staff rudeness",
    reason: "Negative review requires personalized management response",
    status: "pending",
  },
];
